---
output: pdf_document
header-includes:
  - \pagenumbering{gobble} #remove page numbers
  - \usepackage{xcolor} #colors
  - \definecolor{steelblue}{RGB}{70,130,180}
  - \definecolor{firebrick}{RGB}{178,34,34}
geometry: margin=1.5cm #margins
urlcolor: blue #utl colors
params:
  relation: ""
  age: NULL
  parent_age: NA
  penetrance: NULL
  nyears: NULL
  carrier: NULL
  risk: NULL
  date_time: ""
  thedataframe: NULL
---

\begin{center}
{\LARGE \textbf{Genetic Counselling Report for \textit{C9orf72}\textsuperscript{RE}-related ALS-FTD}}\\[1em]
\textit{Report generated on `r params$date_time`}
\end{center}

\vspace{1.5em}

***Warning**: The risk estimates in this report are not definitive predictions. They reflect current knowlegde on age-related penetrance and may be updated as new data become available.*


## Consultand information

\- Relationship to affected individual: `r params$relation`

\- Current age of consultand: `r params$age` years

`r if (!is.na(params$parent_age)) {
  paste0("\n\\- Age of its parent (child of the carrier): ", params$parent_age, " years")
}`

\- Assumed disease penetrance: `r round(params$penetrance * 100)` \%


## Summary of risk estimates

\noindent\fbox{%
  \parbox{\textwidth}{%
    - Estimated probability of carrying the c9orf72RE mutation: \textcolor{steelblue}{\textbf{`r round(params$carrier, 3)`}}\\
    - Estimated probability of developing the disease in the next \textbf{`r params$nyears`} years: \textcolor{firebrick}{\textbf{`r round(params$risk, 3)`}}
  }%
}


## Risk estimates distributions by age


```{r static-plot, echo=FALSE, fig.width=7, fig.height=3.5, fig.align='center', warning=TRUE}

# Plot with ggplot2
library(ggplot2)

ggplot(params$thedataframe, aes(x = Age)) +
  geom_line(aes(y = PvariantWhenHealthy, color = "Carrier probability"), linewidth = 1) +
  geom_line(aes(y = PsickInFuture, color = paste0("Disease risk (next ", params$nyears, " years)")), linewidth = 1) +
  geom_vline(xintercept = params$age, linetype = "dotted", color = "gray40", linewidth=0.6) +
  geom_hline(yintercept = params$carrier, linetype = "dotted", color = "steelblue", linewidth=0.6) +
  geom_hline(yintercept = params$risk, linetype = "dotted", color = "firebrick", linewidth=0.6) + 
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0, 100)) +
  scale_color_manual(values=c("steelblue","firebrick")) +
  theme_light() +
  theme(
    panel.border = element_blank(),
    legend.position = "inside",
    legend.position.inside = c(0.95, 0.95),  # use this instead of legend.position
    legend.justification = c("right", "top"),
    legend.margin = margin(2, 2, 2, 2),
    legend.title = element_blank()
  ) +
  ylab("Probability") + 
  xlab("Age of the consultand")



```


*This report was automatically generated using the online genetic counselling tool available at [https://lbbe-shiny.univ-lyon1.fr/ftd-als/](https://lbbe-shiny.univ-lyon1.fr/ftd-als/). For more details on the computation, please report to the article by de Vienne & de Vienne (in press):* Risk assessment for relatives of carriers of autosomal dominant mutations: theoretical synthesis and application to the C9orf72$^\text{RE}$ variant.


